### ISSUE TITLE
Short references have markdown applied

### ISSUE THREAD

**Issue by Etzos** [LuaDevelopmentTools/luadocumentor#3]
Short references appear to have markdown applied to them which is unfortunate as it messes up the appearance for functions that have multiple underscores in their names.

For example `@{#modulename.name_of_function}` results in modulename.name _of_ function (without the spaces since I can't seem to make GitHub render it properly) when creating the HTML docs.

**Comment by KINFOO** [comment]
Thanks for reporting this.

I will look into it.

**Comment by KINFOO** [comment]
So for this code

```lua
--- A module that allow to manage circle shapes
-- @{circleModule#c_ir_cle}
-- @module circleModule
```

You get this description

> A module that allow to manage circle shapes circleModule#c<em>irc</em>le

**Comment by Etzos** [comment]
That is correct. At least that seems to be the case when I've tested it.
